"""
FLOW Framework
Report Builder

Builds the final HTML report from the template.
"""

import os

from reports.sections import (
    build_executive_summary,
    build_attack_surface,
    build_open_ports,
    build_services,
    build_modules,
    build_findings,
    build_recommendations,
    build_conclusion,
)

from reports.charts import (
    build_risk_distribution,
)


BASE_DIR = os.path.dirname(os.path.abspath(__file__))

TEMPLATE_FILE = os.path.join(
    BASE_DIR,
    "templates",
    "report_template.html",
)


def build_html_report(target, results, findings, stats):
    """
    Build the final HTML report.

    Parameters
    ----------
    target : str
    results : dict
    findings : list
    stats : dict

    Returns
    -------
    str
        Completed HTML report.
    """

    with open(TEMPLATE_FILE, "r", encoding="utf-8") as file:
        html = file.read()

    # --------------------------------------------------
    # Dashboard
    # --------------------------------------------------

    html = html.replace(
        "{{TARGET}}",
        target,
    )

    html = html.replace(
        "{{DATE}}",
        "Generated by FLOW",
    )

    html = html.replace(
        "{{OVERALL_RISK}}",
        stats["overall_risk"],
    )

    html = html.replace(
        "{{TOTAL_FINDINGS}}",
        str(stats["total_findings"]),
    )

    html = html.replace(
        "{{TOTAL_PORTS}}",
        str(stats["total_ports"]),
    )

    html = html.replace(
        "{{TOTAL_SERVICES}}",
        str(stats["total_services"]),
    )

    html = html.replace(
        "{{TOTAL_MODULES}}",
        str(stats["total_modules"]),
    )

    # --------------------------------------------------
    # Report Sections
    # --------------------------------------------------

    html = html.replace(
        "{{EXECUTIVE_SUMMARY}}",
        build_executive_summary(
            target,
            findings,
            stats,
        ),
    )

    html = html.replace(
        "{{ATTACK_SURFACE}}",
        build_attack_surface(results),
    )

    html = html.replace(
        "{{RISK_STATS}}",
        build_risk_distribution(findings),
    )

    html = html.replace(
        "{{OPEN_PORTS}}",
        build_open_ports(results),
    )

    html = html.replace(
        "{{SERVICES}}",
        build_services(results),
    )

    html = html.replace(
        "{{MODULES}}",
        build_modules(results),
    )

    html = html.replace(
        "{{FINDINGS}}",
        build_findings(findings),
    )

    html = html.replace(
        "{{RECOMMENDATIONS}}",
        build_recommendations(findings),
    )

    html = html.replace(
        "{{CONCLUSION}}",
        build_conclusion(
            stats["overall_risk"],
        ),
    )

    return html