"""
FLOW FTP Parser

Parses the raw FTP Enumeration output
generated by Nmap NSE scripts.
"""

import re


def parse_ftp_output(output):
    """
    Parses FTP Enumeration results.

    Parameters:
        output (str): Raw Nmap FTP scan output.

    Returns:
        dict: Parsed FTP information.
    """

    ftp_data = {
        "port": "",
        "state": "",
        "service": "",
        "banner": "",
        "server_os": "",
        "anonymous_login": False,
        "directories": [],
        "risk": "Low",
        "recommendations": []
    }

    lines = output.splitlines()

    # --------------------------------------------------
    # Service Information
    # --------------------------------------------------

    for line in lines:

        line = line.strip()

        # Example:
        # 21/tcp open ftp vsftpd 3.0.3

        match = re.match(
            r"(\d+/tcp)\s+(\w+)\s+(\S+)(.*)",
            line
        )

        if match:

            ftp_data["port"] = match.group(1)
            ftp_data["state"] = match.group(2)
            ftp_data["service"] = match.group(3)

            remaining = match.group(4).strip()

            if remaining:
                ftp_data["banner"] = remaining

        # --------------------------------------------------
        # Anonymous Login
        # --------------------------------------------------

        if "Anonymous FTP login allowed" in line:

            ftp_data["anonymous_login"] = True

        # --------------------------------------------------
        # Banner
        # --------------------------------------------------

        if line.startswith("220"):

            ftp_data["banner"] = line

        # --------------------------------------------------
        # Server Information
        # --------------------------------------------------

        if "UNIX Type" in line:

            ftp_data["server_os"] = line

        # --------------------------------------------------
        # Directory Listing
        # --------------------------------------------------

        if line.startswith("dr") or line.startswith("-"):

            ftp_data["directories"].append(line)

    # --------------------------------------------------
    # Risk Assessment
    # --------------------------------------------------

    risk_score = 0

    if ftp_data["anonymous_login"]:
        risk_score += 2
        ftp_data["recommendations"].append(
            "Disable anonymous FTP login."
        )

    if ftp_data["directories"]:
        risk_score += 1
        ftp_data["recommendations"].append(
            "Review publicly accessible FTP directories."
        )

    if ftp_data["banner"]:
        risk_score += 1
        ftp_data["recommendations"].append(
            "Hide FTP banner information."
        )

    # --------------------------------------------------
    # Overall Risk
    # --------------------------------------------------

    if risk_score >= 4:
        ftp_data["risk"] = "Critical"

    elif risk_score == 3:
        ftp_data["risk"] = "High"

    elif risk_score == 2:
        ftp_data["risk"] = "Medium"

    else:
        ftp_data["risk"] = "Low"

    return ftp_data